export const brends = [
    { value: '', label: 'Tanlang', isDisabled: true },
    { value: 'Boshqa', label: 'Boshqa (Другое)' },
    { value: 'Redmi', label: 'Redmi' },
    { value: 'Infinix', label: 'Infinix' },
    { value: 'Tecno', label: 'Tecno' },
    { value: 'Samsung', label: 'Samsung' },
    { value: 'iPhone', label: 'iPhone' },
    { value: 'Realme', label: 'Realme' },
    { value: 'Poco', label: 'Poco' },
    { value: 'Novey', label: 'Novey' },
    { value: 'Xiaomi', label: 'Xiaomi' },
    { value: 'Huawei', label: 'Huawei' },
    { value: 'Oppo', label: 'Oppo' },
    { value: 'Vivo', label: 'Vivo' },
    { value: 'Google', label: 'Google' },
    { value: 'Motorola', label: 'Motorola' },
    { value: 'OnePlus', label: 'OnePlus' },
    { value: 'Sony', label: 'Sony' },
    { value: 'Lenovo', label: 'Lenovo' },
    { value: 'Asus', label: 'Asus' },
    { value: 'HTC', label: 'HTC' },
    { value: 'Nokia', label: 'Nokia' },
    { value: 'BlackBerry', label: 'BlackBerry' },
    { value: 'LG', label: 'LG' },
    { value: 'Meizu', label: 'Meizu' },
    { value: 'itel', label: 'itel' },
    { value: 'Doogee', label: 'Doogee' },
    { value: 'Honor', label: 'Honor' },
    { value: 'Alcatel', label: 'Alcatel' },
    { value: 'ZTE', label: 'ZTE' },
    { value: 'Coolpad', label: 'Coolpad' },
    { value: 'Artel', label: 'Artel' },
]
